### PR TITLE
fix waiting room orders

### LINKED ISSUE #8: Pos screen - fix changing status of order on waiting screen
- [x] Fix order status "complete"-ing after one of order items timer runs out.
- [x] Fix waiting screen
- [x] Fix orderItems, ordersOrdered subscription

### PR DESCRIPTION
**Pull request by rei2232**

### CODE REVIEW

File: ui/src/modules/waiting/components/OrderDetail.tsx [hunk 1]
```diff
@@ -39,7 +42,7 @@ export default class OrderDetail extends React.Component<Props> {
     const { currentConfig, order, editOrder } = this.props;
     const { uiOptions } = currentConfig;
     const color = uiOptions.colors.primary;
-    const waitingSec = 5 * 60;
+    const waitingSec = 1 * 20;
```
Comment (munkhsaikhan) [inline ui/src/modules/waiting/components/OrderDetail.tsx]: const waitingSec = parseInt(waitingScreen.value) * 60;
